
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deployment
  labels:
    app: cloud
spec:
  replicas: 3  # Number of container replicas
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - name: cloud-container
        image: cloud-ai:latest  # Replace with the name of the Docker image
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
